### ISSUE TITLE
Support App Names with UUID as Suffix

### ISSUE THREAD

**Issue by Kkoile** [cap-js-community/mtx-tool#35]
When using Deploy with Confidence (DwC), cf app names are suffixed with a uuid. This uuid changes with every deployment of our application.  
Because of that we have to setup mtx-tool everytime we want to use it with the correct cf app name.

It would be great if this project could be enhanced and also support DwC style apps.  
One hurdle is that there can be multiple deployed apps with the same base name, but different uuids at the same time. I guess this should not matter too much because they are then different versions of the same app and are bound to the same services. So the logic could choose any app which starts with the configured app name followed by a valid uuid.

mtx-tool is already capable of handling different app names with suffixes `-blue`, `-green` and `-live`. But I guess this is different, because the suffix in our case is not static. One would probably have to work with a regex to filter the correct app name.

**Comment by rlindner81** [comment]
Let's go with a two tier approach. First goal is to support an env variable `MTX_APP_SUFFIX` that gets mixed in with the hard-coded app suffixes `-blue` and `-green`.

Second goal is to support a simple `*` wildcard in the configured app names, that expands into arbitrary app names, but leaves out the known suffixes if they are found.

**Comment by rlindner81** [comment]
@Kkoile When I did the actual implementation, I did not like the wildcard approach so much anymore. I implemented this in a different way now, that I think is more specific to your use-case and slightly less prone to unintended behavior.

The first part with an env variable that can control suffixes works pretty much as we imagined. There was some ordering shenanigans happening, where I had previously gone through all apps and looked for a matching suffix candidate, but since the custom suffix should be checked first it now goes through all suffixes and looks for matching apps instead. This seems to be sensible anyways and lead to fairly intuitive behavior for me.

For the second part, I added a hard-coded suffix `-{UUID}`, which expands into a UUID regex for the suffix check. I feel  this approach is similar to how I handle the `-blue`/`-green` case, by hard-coding them as suffixes to check. Ideally, I want other DwC projects that try the tooling to just work, without thinking a lot about the configuration. I may add a section in the docs on this as well.

Here is a pre-built with the new functionality. Can you try this and see if it works well in practice?
[cap-js-community-mtx-tool-0.7.12.tgz](https://github.com/cap-js-community/mtx-tool/files/12126747/cap-js-community-mtx-tool-0.7.12.tgz)

**Comment by Kkoile** [comment]
I tested it and it works as expected. I only configured the base name of our application and that it connects to the correct cf application.
Thanks a lot for your effort!
