### ISSUE TITLE
 --hdi-enable-tenant

### ISSUE THREAD

**Issue by andre68723** [cap-js-community/mtx-tool#58]
Hi Richard,

a useful addition for future cases would be to enable native tenant (on such database instances) to the service manager which is pretty straightforward

```
PATCH https://service-manager.cfapps.eu10.hana.ondemand.com/v1/service_instances/ Body: { "parameters": { "enableTenant": true } }
```
Similar to `cdsua` maybe
* `hdiet   --hdi-enable-tenant [TENANT_ID] enable native tenant`
* `hdieta           enable native tenant for all hdi containers`   

Thanks, Andre

**Comment by rlindner81** [comment]
Hi Andre! Native HANA tenants are SAP internal only, so we did not include them or the enablement so far... but upon more reflection, I now agree with you that there should be a command to do this properly--particularly since it is a topX requirement.

There are some subtleties that the MTX tool can do well. Most prominent, the related container bindings should be deleted before the enablement and re-created after.

For the command itself, I like the syntax: `--hdi-enable-tenant [TENANT_ID]`, where it will enable all tenants, when no particular tenant_id is specified. Due to the binding deletion, this will be considered a "dangerous" command, with no short-form.

**Comment by andre68723** [comment]
great news,  one minor remark:

`v1/service_bindings` returns now a additional field `tenantId` in the **credentials** section.
Eventually it makes sense to add this to the table output of `hdil   --hdi-list`. 

Catch is only that the current has already a `tenant_id` which is a different meaning. Maybe `tenantId (database)`?

<img width="198" alt="Bildschirmfoto 2024-02-12 um 12 23 00" src="https://github.com/cap-js-community/mtx-tool/assets/16468234/be9a61c1-b48a-4e18-8461-4e4df79bb7a8">

**Comment by rlindner81** [comment]
That is curious... what is this database "tenant id" used for?
